# Generated by Django 4.1.7 on 2023-03-22 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Давление', models.IntegerField(default=0)),
                ('Температура', models.IntegerField(default=0)),
                ('Влажность', models.IntegerField(default=0)),
                ('Объем в первой колбе', models.IntegerField(default=0)),
                ('Объем во второй колбе', models.IntegerField(default=0)),
                ('Яркость света', models.IntegerField(default=0)),
                ('Уровень углекислого газа', models.IntegerField(default=0)),
                ('Уровень других газов', models.IntegerField(default=0)),
                ('Сколько воды прошло', models.IntegerField(default=0)),
                ('Переполнение, тревога', models.BooleanField(default=False)),
                ('Тревога всех газов', models.BooleanField(default=False)),
                ('Углекислый гах, тревога', models.BooleanField(default=False)),
                ('Дверь', models.BooleanField(default=False)),
                ('Работает ли лаборатория', models.BooleanField(default=False)),
                ('Работает ли вентилятор', models.BooleanField(default=False)),
                ('Окно', models.BooleanField(default=False)),
                ('Скорость вентилятора', models.BooleanField(default=False)),
                ('Гироскоп', models.IntegerField(default=0)),
                ('Освещенность в комнате', models.IntegerField(default=0)),
                ('Запрошенный цвет', models.CharField(blank=True, choices=[('Gold', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Black', 'Black')], max_length=6)),
                ('РГБ, значение жидкости', models.CharField(max_length=11)),
                ('Цвет жидкости', models.CharField(choices=[('Gold', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Black', 'Black')], max_length=6)),
                ('Люди в лаборатории', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('labs', models.ManyToManyField(to='lab.lab')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
