# Generated by Django 4.1.7 on 2023-03-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='РГБ, значение жидкости',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='lab',
            name='Цвет жидкости',
            field=models.CharField(blank=True, choices=[('Gold', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Black', 'Black')], max_length=6),
        ),
    ]
