# Generated by Django 4.1.7 on 2023-03-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_lab_ргб, значение жидкости_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='РГБ, значение жидкости',
            new_name='RGB',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Влажность',
            new_name='bar',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Гироскоп',
            new_name='co2',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Дверь',
            new_name='co2Alert',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Запрошенный цвет',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Давление',
            new_name='countWater',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Окно',
            new_name='door',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Объем в первой колбе',
            new_name='emission_pr',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Объем во второй колбе',
            new_name='gyroscope',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Освещенность в комнате',
            new_name='heighWaterFirst',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Сколько воды прошло',
            new_name='heighWaterSecond',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Температура',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Уровень других газов',
            new_name='light_level',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Цвет жидкости',
            new_name='light_request',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Уровень углекислого газа',
            new_name='lux',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Переполнение, тревога',
            new_name='otherGasAlert',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Работает ли вентилятор',
            new_name='pumpAlert',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Работает ли лаборатория',
            new_name='start_lab',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Яркость света',
            new_name='temperature',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Скорость вентилятора',
            new_name='went',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Тревога всех газов',
            new_name='went_speed',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='Углекислый гах, тревога',
            new_name='window',
        ),
    ]
